services:

  # namenode:
  #   image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
  #   container_name: namenode
  #   ports:
  #     - "9870:9870"
  #   volumes:
  #     - ./tmp/hadoop-namenode:/hadoop/dfs/name
  #     - ./hadoop/data:/hadoop-data
  #   hostname: namenode
  #   environment:
  #     CLUSTER_NAME: hadoop

  # datanode:
  #   image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
  #   container_name: datanode
  #   environment:
  #     CLUSTER_NAME: hadoop
  #     CORE_CONF_fs_defaultFS: hdfs://namenode:8020
  #   volumes:
  #     - ./tmp/hadoop-datanode:/hadoop/dfs/data
  #   depends_on:
  #     - namenode

  spark-master:
    container_name: spark-master
    extends:
      file: spark-compose.yaml
      service: spark-master
  spark-worker:
    container_name: spark-worker
    extends:
      file: spark-compose.yaml
      service: spark-worker
networks:
  default:
    name: wine-network